# Jekyll 설정 파일입니다.
# 이 파일을 변경하면 서버를 재시작해야 합니다.

# 기본 사이트 설정
locale: "ko-KR"
site_theme: "air" # 현재 사용 가능한 테마: "default", "air"
title: "정이든 / Site Title"
title_separator: "-"
name: &name "정이든"
description: &description "정이든's academic portfolio" # 페이지에 별도 설명이 없을 경우 사용될 사이트의 기본 설명입니다.
url: https://eden096.github.io # 사이트의 기본 호스트 이름 및 프로토콜입니다.
baseurl: "" # 사이트의 하위 경로입니다. (예: "/blog")
repository: "eden096/eden096.github.io"

# 사이트 저자 - 사이드바의 저자 정보란에 표시될 내용을 관리합니다.
author:
  avatar: "profile.jpg"
  name: "정이든"
  bio: "컴퓨터에 항상 열정을 가진 학생입니다."
  location: "경기도 수원시 장안구"
  employer: "한신대학교"
  email: "jungeden0906@gmail.com"
  github: "eden096"
  phone: "010-9885-7796"
  instagram: "eden_096"

# 출판물 카테고리 - 출판물 카테고리 목록과 제목을 설정합니다. (현재 사용되지 않음)
publication_category:
  books:
    title: 'Books'
  manuscripts:
    title: 'Journal Articles'
  conferences:
    title: 'Conference Papers'

# 사이트 설정
words_per_minute: 160 # 분당 단어 수 (글 읽는 시간 계산용)
future: true # 미래 날짜의 게시물도 빌드할지 여부
read_more: "disabled" # 활성화하면, 발췌문에 "더 읽기" 링크가 추가됩니다.
comments:
  provider: false # 댓글 기능 제공자 (false, "disqus", "discourse" 등)
staticman:
  branch: "gh-pages" # Staticman 댓글이 저장될 브랜치
atom_feed:
  hide: false # 푸터에 RSS 피드 링크를 숨길지 여부

# 분석
analytics:
  provider: "false" # 분석 도구 제공자 (false, "google", "custom" 등)

# 파일 읽기 설정
include: # 빌드 시 포함할 파일 및 폴더
  - .htaccess
  - _pages
  - files
exclude: # 빌드 시 제외할 파일 및 폴더
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .github
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - CHANGELOG
  - Capfile
  - config
  - Dockerfile
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - local
  - log
  - node_modules
  - package.json*
  - Rakefile
  - README
  - tmp
  - vendor
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# 변환 설정
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n" # 발췌문 구분자
incremental: false

# 마크다운 처리 설정
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# 템플릿에서 사용하는 컬렉션 유형을 제어하는 설정입니다.
collections:
  study_log:
    output: false
    permalink: /:collection/:path/
  baekjoon:
    output: true
    permalink: /:collection/:path/
  future_activities:
    output: false
    permalink: /:collection/:path/
  journey:
    output: true
    permalink: /:collection/:path/

# 페이지와 컬렉션이 사이트에 포함되는 방식을 제어하는 설정입니다.
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: false
      related: true
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: study_log
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  - scope:
      path: ""
      type: baekjoon
    values:
      layout: single
      author_profile: true
      share: false
      comments: true
  - scope:
      path: ""
      type: future_activities
    values:
      layout: single
      author_profile: true
      share: true
      comment: true
  - scope:
      path: ""
      type: journey
    values:
      layout: talk
      author_profile: true
      share: false

# Sass/SCSS 설정
sass:
  sass_dir: _sass
  style: compressed # CSS 출력 스타일

# 출력 설정
permalink: /:categories/:title/ # 고유 주소 형식
timezone: Etc/UTC # 시간대

# 플러그인
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

# --safe 옵션으로 GitHub Pages 환경 흉내내기
whitelist:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

# 아카이브 페이지 설정
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML 압축 설정
compress_html:
  clippings: all
  ignore:
    envs: development
